// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePromptColdStart = "PromptColdStart"

// PromptColdStart mapped from table <PromptColdStart>
type PromptColdStart struct {
	ID         string     `gorm:"column:id;type:text;primaryKey" json:"id"`
	PromptID   string     `gorm:"column:promptId;type:text;not null;uniqueIndex:PromptColdStart_promptId_key,priority:1" json:"promptId"`
	Source     string     `gorm:"column:source;type:"PromptColdStartSource";not null" json:"source"`
	CreatedAt  *time.Time `gorm:"column:createdAt;type:timestamp(3) with time zone;default:CURRENT_TIMESTAMP" json:"createdAt"`
	Impression int32      `gorm:"column:impression;type:integer;not null" json:"impression"`
	Status     int32      `gorm:"column:status;type:integer;not null" json:"status"`
	ExitedAt   *time.Time `gorm:"column:exitedAt;type:timestamp(3) with time zone" json:"exitedAt"`
}

// TableName PromptColdStart's table name
func (*PromptColdStart) TableName() string {
	return TableNamePromptColdStart
}
